apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: drop-commerce-frontend-config
  namespace: drop-commerce
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
